Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # An example hook script to verify what is about to be committed.
 # Called by "git commit" with no arguments.  The hook should
@@ -7,7 +7,16 @@
 #
 # To enable this hook, rename this file to "pre-commit".
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
+exec < /dev/tty
+read -p "Did you squash your commits? [yN]: " yn
+case $yn in
+    [Yy]* ) echo "Ok, your good to go";;
+    * ) echo "What are you waiting for then?" && exit 1;;
+esac
+
+
+
+if git rev-parse --verify HEAD >/dev/null 3>&1
 then
 	against=HEAD
 else
@@ -45,27 +54,18 @@ EOF
 	exit 1
 fi
 
-# 20181108 Tried and tried, but this doesn't seem to work? At least far as *I* know...
+
 # If there are whitespace errors, print the offending file names and fail.
+# 20181108 Tried and tried, but this doesn't seem to work? At least as *I* know...
 #exec git diff-index --check --cached $against --
 
-
-# Check Javascript for debugger statements AND files with a BOM?
-for FILE in `git diff-index --check --cached $against -- | cut -c3-` ; do
-    # Check if the file contains 'debugger'
-    if [ "grep 'debugger' $FILE" ]
-    then
-        echo $FILE ' contains debugger!'
-        exit 1
-    fi
-
-    if [ "grep -rlI $'\xEF\xBB\xBF'  $FILE" ]
-		then
-        echo $FILE ' has a BOM ??!'
-        exit 1
+git diff --cached --no-renames --diff-filter=AM --name-only -- '*.java' |
+(status=0; while IFS= read path; do
+    if git show ":$path" | head -1 | grep $'^\xEF\xBB\xBF' >/dev/null; then
+        echo "Error: file '$path' starts with Unicode BOM.'"
+        status=1
     fi
 done
-exit
-
+exit $status)
 
 
